import { useEffect, useRef, useState } from "react";
import {
  collection,
  getDocs,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
  Timestamp,
  query,
  where
} from "firebase/firestore";
import { db } from "../../firebase";

export default function EventsManager() {
  const [events, setEvents] = useState([]);
  const [manualEvents, setManualEvents] = useState([]);
  const [autoEvents, setAutoEvents] = useState([]);

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [eventDate, setEventDate] = useState("");
  const [time, setTime] = useState("");
  const [location, setLocation] = useState("");
  const [image, setImage] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [editingId, setEditingId] = useState(null);

  const fileRef = useRef(null);

  const fetchEvents = async () => {
    try {
      const snap = await getDocs(collection(db, "events"));
      const data = snap.docs.map(d => ({ id: d.id, ...d.data() }));

      const manual = data.filter(e => !e.autoGenerated);
      const auto = data.filter(e => e.autoGenerated);

      setEvents(data);
      setManualEvents(manual);
      setAutoEvents(auto);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    fetchEvents();
  }, []);

  const uploadImage = async (file) => {
    const formData = new FormData();
    formData.append("file", file);
    formData.append("upload_preset", "Lepanto");

    const res = await fetch(
      "https://api.cloudinary.com/v1_1/dxcwgsjvk/image/upload",
      { method: "POST", body: formData }
    );
    const data = await res.json();
    return data.secure_url;
  };

  const addEvent = async () => {
    if (!title || !description || !eventDate) return alert("Required fields missing");

    setUploading(true);

    try {
      let imageUrl = "";
      if (image) imageUrl = await uploadImage(image);

      await addDoc(collection(db, "events"), {
        title,
        description,
        eventDate: Timestamp.fromDate(new Date(eventDate + " " + (time || "00:00"))),
        location: location || "",
        imageUrl,
        autoGenerated: false,
        createdAt: Timestamp.now()
      });

      resetForm();
      fetchEvents();
      alert("Manual event added successfully!");
    } catch (err) {
      console.error(err);
      alert("Failed to add event");
    } finally {
      setUploading(false);
    }
  };

  const startEditing = (event) => {
    setEditingId(event.id);
    setTitle(event.title);
    setDescription(event.description);
    setEventDate(event.eventDate?.toDate().toISOString().split('T')[0] || "");
    setTime(event.time || "");
    setLocation(event.location || "");
  };

  const saveEdit = async () => {
    if (!editingId) return;

    setUploading(true);

    try {
      let imageUrl = "";

      if (image) {
        imageUrl = await uploadImage(image);
      }

      const updateData = {
        title,
        description,
        eventDate: Timestamp.fromDate(new Date(eventDate + " " + (time || "00:00"))),
        location: location || "",
      };

      if (imageUrl) {
        updateData.imageUrl = imageUrl;
      }

      await updateDoc(doc(db, "events", editingId), updateData);

      resetForm();
      fetchEvents();
      alert("Event updated successfully!");
    } catch (err) {
      console.error(err);
      alert("Failed to update event");
    } finally {
      setUploading(false);
    }
  };

  const resetForm = () => {
    setTitle("");
    setDescription("");
    setEventDate("");
    setTime("");
    setLocation("");
    setImage(null);
    setEditingId(null);
    if (fileRef.current) fileRef.current.value = "";
  };

  const deleteEvent = async (id) => {
    if (!confirm("Delete this event?")) return;

    try {
      await deleteDoc(doc(db, "events", id));
      fetchEvents();
      alert("Event deleted.");
    } catch (err) {
      console.error(err);
      alert("Failed to delete event");
    }
  };

  const cleanupDuplicates = async () => {
    if (!confirm("Remove duplicate events?")) return;

    try {
      const snap = await getDocs(collection(db, "events"));
      const seen = new Map();
      let deletedCount = 0;

      for (const docSnap of snap.docs) {
        const data = docSnap.data();
        const key = `${data.sourceRuleId || 'manual'}-${data.eventDate?.seconds || 0}`;

        if (seen.has(key)) {
          await deleteDoc(doc(db, "events", docSnap.id));
          deletedCount++;
        } else {
          seen.set(key, true);
        }
      }

      fetchEvents();
      alert(`Removed ${deletedCount} duplicates.`);
    } catch (err) {
      console.error(err);
      alert("Cleanup failed");
    }
  };

  return (
    <div className="space-y-8">
      <h2 className="text-3xl font-bold text-blue-900">Events Manager</h2>

      <div className="flex gap-3">
        <button onClick={cleanupDuplicates} className="bg-red-600 text-white px-6 py-3 rounded">
          Cleanup Duplicates
        </button>
      </div>

      {/* Manual Add / Edit Form */}
      <div className="bg-white p-6 rounded-xl shadow border">
        <h3 className="font-bold mb-4">{editingId ? "Edit Event" : "Add Manual Event"}</h3>
        <input className="w-full border p-3 rounded mb-3" placeholder="Title" value={title} onChange={e => setTitle(e.target.value)} />
        <textarea className="w-full border p-3 rounded mb-3" rows={3} placeholder="Description" value={description} onChange={e => setDescription(e.target.value)} />
        <input className="w-full border p-3 rounded mb-3" type="date" value={eventDate} onChange={e => setEventDate(e.target.value)} />
        <input className="w-full border p-3 rounded mb-3" type="time" value={time} onChange={e => setTime(e.target.value)} />
        <input className="w-full border p-3 rounded mb-3" placeholder="Location" value={location} onChange={e => setLocation(e.target.value)} />
        <input ref={fileRef} type="file" className="w-full border p-3 rounded mb-5" onChange={e => setImage(e.target.files[0])} />

        <div className="flex gap-3">
          <button onClick={editingId ? saveEdit : addEvent} disabled={uploading} className="flex-1 bg-blue-700 text-white py-3 rounded font-bold">
            {uploading ? "Saving..." : editingId ? "Save Changes" : "Add Manual Event"}
          </button>
          {editingId && (
            <button onClick={resetForm} className="flex-1 bg-gray-600 text-white py-3 rounded font-bold">
              Cancel
            </button>
          )}
        </div>
      </div>

      {/* Manual Events */}
      <div>
        <h3 className="font-semibold mb-4">Manual Events ({manualEvents.length})</h3>
        {manualEvents.map(event => (
          <div key={event.id} className="bg-white border rounded-xl p-6 mb-4 flex justify-between items-start">
            <div>
              <h4 className="font-bold">{event.title}</h4>
              <p className="text-gray-600">{event.description}</p>
              <p className="text-sm text-gray-500">📅 {event.eventDate?.toDate().toDateString()}</p>
              {event.imageUrl && <p className="text-xs text-gray-400">Has Image</p>}
            </div>
            <div className="flex gap-2">
              <button onClick={() => startEditing(event)} className="bg-blue-600 text-white px-4 py-2 rounded">Edit</button>
              <button onClick={() => deleteEvent(event.id)} className="bg-red-600 text-white px-4 py-2 rounded">Delete</button>
            </div>
          </div>
        ))}
      </div>

      {/* Auto Generated Events */}
      <div>
        <h3 className="font-semibold mb-4">Auto-Generated Events ({autoEvents.length})</h3>
        {autoEvents.map(event => (
          <div key={event.id} className="bg-white border rounded-xl p-6 mb-4 flex justify-between items-start">
            <div>
              <h4 className="font-bold">{event.title}</h4>
              <p className="text-gray-600">{event.description}</p>
              <p className="text-sm text-gray-500">📅 {event.eventDate?.toDate().toDateString()} (Auto)</p>
            </div>
            <button onClick={() => deleteEvent(event.id)} className="bg-red-600 text-white px-4 py-2 rounded">Delete</button>
          </div>
        ))}
      </div>
    </div>
  );
}