import { useEffect, useRef, useState } from "react";
import {
  collection,
  getDocs,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
  Timestamp,
} from "firebase/firestore";
import { db } from "../../firebase";

export default function EventsManager() {
  const [events, setEvents] = useState([]);
  const [manualEvents, setManualEvents] = useState([]);
  const [autoEvents, setAutoEvents] = useState([]);
  const [loading, setLoading] = useState(true);

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [eventDate, setEventDate] = useState("");
  const [time, setTime] = useState("");
  const [location, setLocation] = useState("");
  const [image, setImage] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [editingId, setEditingId] = useState(null);

  const fileRef = useRef(null);

  const fetchEvents = async () => {
    setLoading(true);
    try {
      const snap = await getDocs(collection(db, "events"));
      const data = snap.docs.map(d => ({ id: d.id, ...d.data() }));

      // Sort by date (soonest first)
      const sortedData = data.sort((a, b) => {
        const dateA = a.eventDate?.toDate?.() || new Date(0);
        const dateB = b.eventDate?.toDate?.() || new Date(0);
        return dateA - dateB;
      });

      const manual = sortedData.filter(e => !e.autoGenerated);
      const auto = sortedData.filter(e => e.autoGenerated);

      setEvents(sortedData);
      setManualEvents(manual);
      setAutoEvents(auto);
    } catch (err) {
      console.error(err);
    }
    setLoading(false);
  };

  useEffect(() => {
    fetchEvents();
  }, []);

  const uploadImage = async (file) => {
    const formData = new FormData();
    formData.append("file", file);
    formData.append("upload_preset", "Lepanto");

    const res = await fetch("https://api.cloudinary.com/v1_1/dxcwgsjvk/image/upload", {
      method: "POST",
      body: formData,
    });
    const data = await res.json();
    return data.secure_url;
  };

  const addEvent = async () => {
    if (!title || !description || !eventDate) return alert("Title, Description and Date are required");

    setUploading(true);
    try {
      let imageUrl = "";
      if (image) imageUrl = await uploadImage(image);

      await addDoc(collection(db, "events"), {
        title,
        description,
        eventDate: Timestamp.fromDate(new Date(`${eventDate}T${time || "00:00"}`)),
        location: location || "",
        imageUrl,
        autoGenerated: false,
        createdAt: Timestamp.now()
      });

      resetForm();
      fetchEvents();
      alert("Manual event added successfully!");
    } catch (err) {
      console.error(err);
      alert("Failed to add event");
    } finally {
      setUploading(false);
    }
  };

  const startEditing = (event) => {
    setEditingId(event.id);
    setTitle(event.title || "");
    setDescription(event.description || "");
    setEventDate(event.eventDate?.toDate().toISOString().split("T")[0] || "");
    setTime(event.time || "");
    setLocation(event.location || "");
  };

  const saveEdit = async () => {
    if (!editingId) return;

    setUploading(true);
    try {
      let imageUrl = "";
      if (image) imageUrl = await uploadImage(image);

      const updateData = {
        title,
        description,
        eventDate: Timestamp.fromDate(new Date(`${eventDate}T${time || "00:00"}`)),
        location: location || "",
      };

      if (imageUrl) updateData.imageUrl = imageUrl;

      await updateDoc(doc(db, "events", editingId), updateData);

      resetForm();
      fetchEvents();
      alert("Event updated successfully!");
    } catch (err) {
      console.error(err);
      alert("Failed to update event");
    } finally {
      setUploading(false);
    }
  };

  const resetForm = () => {
    setTitle("");
    setDescription("");
    setEventDate("");
    setTime("");
    setLocation("");
    setImage(null);
    setEditingId(null);
    if (fileRef.current) fileRef.current.value = "";
  };

  const deleteEvent = async (id) => {
    if (!confirm("Delete this event?")) return;
    try {
      await deleteDoc(doc(db, "events", id));
      fetchEvents();
    } catch (err) {
      alert("Failed to delete event");
    }
  };

  const cleanupDuplicates = async () => {
    if (!confirm("Remove duplicate events?")) return;

    try {
      const snap = await getDocs(collection(db, "events"));
      const seen = new Map();
      let deletedCount = 0;

      for (const docSnap of snap.docs) {
        const data = docSnap.data();
        const key = `${data.sourceRuleId || "manual"}-${data.eventDate?.seconds || 0}`;

        if (seen.has(key)) {
          await deleteDoc(doc(db, "events", docSnap.id));
          deletedCount++;
        } else {
          seen.set(key, true);
        }
      }

      fetchEvents();
      alert(`Removed ${deletedCount} duplicate events.`);
    } catch (err) {
      alert("Cleanup failed");
    }
  };

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-center">
        <h2 className="text-3xl font-bold text-blue-900">Events Manager</h2>
        <button 
          onClick={cleanupDuplicates} 
          className="bg-red-600 hover:bg-red-700 text-white px-5 py-2.5 rounded-xl font-medium"
        >
          Cleanup Duplicates
        </button>
      </div>

      {/* Add / Edit Form */}
      <div className="bg-white border border-gray-200 p-6 rounded-2xl shadow-sm">
        <h3 className="font-bold text-xl mb-5 text-blue-900">
          {editingId ? "Edit Event" : "Add Manual Event"}
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <input className="border p-3 rounded-xl" placeholder="Event Title" value={title} onChange={e => setTitle(e.target.value)} />
          <input className="border p-3 rounded-xl" type="date" value={eventDate} onChange={e => setEventDate(e.target.value)} />
          <input className="border p-3 rounded-xl" type="time" value={time} onChange={e => setTime(e.target.value)} />
          <input className="border p-3 rounded-xl" placeholder="Location" value={location} onChange={e => setLocation(e.target.value)} />
        </div>

        <textarea 
          className="w-full border p-3 rounded-xl mt-4" 
          rows={3} 
          placeholder="Description" 
          value={description} 
          onChange={e => setDescription(e.target.value)} 
        />

        <div className="mt-4">
          <label className="text-sm text-gray-600 mb-1 block">Event Image (optional)</label>
          <input ref={fileRef} type="file" accept="image/*" onChange={e => setImage(e.target.files[0])} className="w-full border p-3 rounded-xl" />
        </div>

        <div className="flex gap-3 mt-6">
          <button 
            onClick={editingId ? saveEdit : addEvent} 
            disabled={uploading}
            className="flex-1 bg-blue-700 hover:bg-blue-800 disabled:bg-blue-400 text-white py-3 rounded-xl font-semibold transition"
          >
            {uploading ? "Saving..." : editingId ? "Save Changes" : "Add Manual Event"}
          </button>

          {editingId && (
            <button onClick={resetForm} className="flex-1 bg-gray-500 hover:bg-gray-600 text-white py-3 rounded-xl font-semibold">
              Cancel
            </button>
          )}
        </div>
      </div>

      {/* Manual Events - Sorted by Date */}
      <div>
        <h3 className="font-semibold text-lg mb-4 text-gray-700">Manual Events ({manualEvents.length})</h3>
        
        {loading ? (
          <p className="text-gray-500">Loading events...</p>
        ) : manualEvents.length === 0 ? (
          <p className="text-gray-500">No manual events added yet.</p>
        ) : (
          <div className="space-y-4">
            {manualEvents.map(event => (
              <div key={event.id} className="bg-white border border-gray-200 p-5 rounded-2xl flex flex-col md:flex-row justify-between gap-4">
                <div>
                  <h4 className="font-bold text-lg text-blue-900">{event.title}</h4>
                  <p className="text-gray-600 mt-1">{event.description}</p>
                  <div className="text-sm text-gray-500 mt-2">
                    📅 {event.eventDate?.toDate().toDateString()} 
                    {event.time && ` • ${event.time}`}
                    {event.location && ` • ${event.location}`}
                  </div>
                </div>
                <div className="flex gap-2 items-start">
                  <button onClick={() => startEditing(event)} className="bg-yellow-500 hover:bg-yellow-600 text-white px-4 py-2 rounded-xl text-sm">Edit</button>
                  <button onClick={() => deleteEvent(event.id)} className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-xl text-sm">Delete</button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Auto-Generated Events - Sorted by Date */}
      <div>
        <h3 className="font-semibold text-lg mb-4 text-gray-700">Auto-Generated Events ({autoEvents.length})</h3>
        
        {loading ? (
          <p className="text-gray-500">Loading...</p>
        ) : autoEvents.length === 0 ? (
          <p className="text-gray-500">No auto-generated events yet.</p>
        ) : (
          <div className="space-y-4">
            {autoEvents.map(event => (
              <div key={event.id} className="bg-white border border-gray-200 p-5 rounded-2xl flex flex-col md:flex-row justify-between gap-4">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <h4 className="font-bold text-lg text-blue-900">{event.title}</h4>
                    <span className="text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded-full">Auto</span>
                  </div>
                  <p className="text-gray-600">{event.description}</p>
                  <div className="text-sm text-gray-500 mt-2">
                    📅 {event.eventDate?.toDate().toDateString()}
                    {event.time && ` • ${event.time}`}
                    {event.location && ` • ${event.location}`}
                  </div>
                </div>
                <div>
                  <button onClick={() => deleteEvent(event.id)} className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-xl text-sm">
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}