import { useEffect, useState } from "react";
import {
  collection,
  getDocs,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
  Timestamp,
  query,
  where
} from "firebase/firestore";

import { db } from "../../firebase";

export default function EventRulesManager() {
  const [eventRules, setEventRules] = useState([]);
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);

  // Add Form
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [type, setType] = useState("weekly");
  const [dayOfWeek, setDayOfWeek] = useState("sunday");
  const [weekOfMonth, setWeekOfMonth] = useState(1);
  const [date, setDate] = useState("");
  const [time, setTime] = useState("");
  const [location, setLocation] = useState("");

  // Edit Form
  const [editingId, setEditingId] = useState(null);
  const [editTitle, setEditTitle] = useState("");
  const [editDescription, setEditDescription] = useState("");
  const [editType, setEditType] = useState("weekly");
  const [editDayOfWeek, setEditDayOfWeek] = useState("sunday");
  const [editWeekOfMonth, setEditWeekOfMonth] = useState(1);
  const [editDate, setEditDate] = useState("");
  const [editTime, setEditTime] = useState("");
  const [editLocation, setEditLocation] = useState("");

  const fetchRules = async () => {
    setLoading(true);
    try {
      const snapshot = await getDocs(collection(db, "eventRules"));
      const data = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      setEventRules(data);
    } catch (err) {
      console.error(err);
    }
    setLoading(false);
  };

  useEffect(() => {
    fetchRules();
  }, []);

  const generateNextDate = (rule) => {
    const today = new Date();
    let next = new Date(today);

    if (rule.type === "weekly") {
      const days = { sunday: 0, monday: 1, tuesday: 2, wednesday: 3, thursday: 4, friday: 5, saturday: 6 };
      const targetDay = days[rule.dayOfWeek];
      let diff = targetDay - today.getDay();
      if (diff < 0) diff += 7;
      next.setDate(today.getDate() + diff);
    } else if (rule.type === "monthly") {
      next.setDate(1);
      next.setDate((rule.weekOfMonth - 1) * 7 + 1);
      const targetDay = { sunday: 0, monday: 1, tuesday: 2, wednesday: 3, thursday: 4, friday: 5, saturday: 6 }[rule.dayOfWeek];
      let diff = targetDay - next.getDay();
      if (diff < 0) diff += 7;
      next.setDate(next.getDate() + diff);
    } else if (rule.type === "fixed") {
      next = new Date(rule.date);
    }

    if (rule.time) {
      const [h, m] = rule.time.split(":").map(Number);
      next.setHours(h, m || 0);
    }

    return next;
  };

const createOrUpdateEvent = async (rule, ruleId) => {
  try {
    for (let i = 0; i < 8; i++) { // Next 8 weeks
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + i * 7);

      let eventDate;

      if (rule.type === "weekly") {
        const days = { sunday: 0, monday: 1, tuesday: 2, wednesday: 3, thursday: 4, friday: 5, saturday: 6 };
        const targetDay = days[rule.dayOfWeek];
        eventDate = new Date(futureDate);
        let diff = targetDay - eventDate.getDay();
        if (diff < 0) diff += 7;
        eventDate.setDate(eventDate.getDate() + diff);
      } else if (rule.type === "monthly") {
        eventDate = new Date(futureDate);
        eventDate.setDate((rule.weekOfMonth - 1) * 7 + 1);
        const targetDay = { sunday: 0, monday: 1, tuesday: 2, wednesday: 3, thursday: 4, friday: 5, saturday: 6 }[rule.dayOfWeek];
        let diff = targetDay - eventDate.getDay();
        if (diff < 0) diff += 7;
        eventDate.setDate(eventDate.getDate() + diff);
      } else if (rule.type === "fixed") {
        eventDate = new Date(rule.date);
      }

      if (rule.time) {
        const [h, m] = rule.time.split(":").map(Number);
        eventDate.setHours(h, m || 0);
      }

      // Strong duplicate check by rule + exact date
      const q = query(
        collection(db, "events"),
        where("sourceRuleId", "==", ruleId),
        where("eventDate", "==", Timestamp.fromDate(eventDate))
      );

      const snap = await getDocs(q);

      if (snap.empty) {
        await addDoc(collection(db, "events"), {
          title: rule.title,
          description: rule.description || "",
          location: rule.location || "",
          time: rule.time || "",
          imageUrl: "",
          sourceRuleId: ruleId,
          autoGenerated: true,
          eventDate: Timestamp.fromDate(eventDate),
          createdAt: Timestamp.now()
        });
      }
    }
  } catch (err) {
    console.error(err);
  }
};
const generateThisWeekEvents = async () => {
  if (!confirm("Generate events for this week from all rules?")) return;

  setUploading(true);

  try {
    for (const rule of eventRules) {
      await createOrUpdateEvent(rule, rule.id);
    }
    alert("Events generated for this week!");
    fetchRules();
  } catch (err) {
    console.error(err);
    alert("Failed to generate events");
  } finally {
    setUploading(false);
  }
};

  const addRule = async () => {
    if (!title.trim()) return alert("Title is required");

    setUploading(true);

    try {
      const newRuleRef = await addDoc(collection(db, "eventRules"), {
        title,
        description,
        type,
        dayOfWeek,
        weekOfMonth: Number(weekOfMonth),
        date,
        time,
        location,
        active: true,
        createdAt: Timestamp.now()
      });

      await createOrUpdateEvent({
        title,
        description,
        type,
        dayOfWeek,
        weekOfMonth: Number(weekOfMonth),
        date,
        time,
        location
      }, newRuleRef.id);

      fetchRules();
      alert("Rule added and event generated!");

      setTitle("");
      setDescription("");
      setType("weekly");
      setDayOfWeek("sunday");
      setWeekOfMonth(1);
      setDate("");
      setTime("");
      setLocation("");
    } catch (err) {
      console.error(err);
      alert("Failed to add rule");
    } finally {
      setUploading(false);
    }
  };

  const startEditing = (rule) => {
    setEditingId(rule.id);
    setEditTitle(rule.title || "");
    setEditDescription(rule.description || "");
    setEditType(rule.type || "weekly");
    setEditDayOfWeek(rule.dayOfWeek || "sunday");
    setEditWeekOfMonth(rule.weekOfMonth || 1);
    setEditDate(rule.date || "");
    setEditTime(rule.time || "");
    setEditLocation(rule.location || "");
  };

  const saveRule = async (id) => {
    try {
      await updateDoc(doc(db, "eventRules", id), {
        title: editTitle,
        description: editDescription,
        type: editType,
        dayOfWeek: editDayOfWeek,
        weekOfMonth: Number(editWeekOfMonth),
        date: editDate,
        time: editTime,
        location: editLocation,
      });

      await createOrUpdateEvent({
        title: editTitle,
        description: editDescription,
        type: editType,
        dayOfWeek: editDayOfWeek,
        weekOfMonth: Number(editWeekOfMonth),
        date: editDate,
        time: editTime,
        location: editLocation
      }, id);

      setEditingId(null);
      fetchRules();
      alert("Rule updated successfully.");
    } catch (err) {
      console.error(err);
      alert("Failed to update rule");
    }
  };

  const cancelEditing = () => setEditingId(null);

  const removeRule = async (id) => {
    if (!confirm("Delete this rule?")) return;

    try {
      const q = query(collection(db, "events"), where("sourceRuleId", "==", id));
      const snap = await getDocs(q);
      for (const d of snap.docs) await deleteDoc(doc(db, "events", d.id));

      await deleteDoc(doc(db, "eventRules", id));
      fetchRules();
      alert("Rule deleted.");
    } catch (err) {
      console.error(err);
    }
  };

  const cleanupDuplicates = async () => {
  if (!confirm("Remove duplicate events? This cannot be undone.")) return;

  setUploading(true);

  try {
    const eventsSnap = await getDocs(collection(db, "events"));
    const eventsMap = new Map();

    // Group by sourceRuleId + eventDate
    eventsSnap.docs.forEach(doc => {
      const data = doc.data();
      const key = `${data.sourceRuleId}-${data.eventDate?.seconds}`;
      if (eventsMap.has(key)) {
        // Delete duplicate
        deleteDoc(doc(db, "events", doc.id));
      } else {
        eventsMap.set(key, doc.id);
      }
    });

    alert("Duplicates cleaned up!");
    fetchRules(); // Refresh if needed
  } catch (err) {
    console.error(err);
    alert("Cleanup failed");
  } finally {
    setUploading(false);
  }
};

  return (
    <div className="space-y-8">
      <h2 className="text-3xl font-bold text-blue-900">Event Rules Manager</h2>

      {/* Generate This Week Button */}
      <button 
        onClick={generateThisWeekEvents}
        className="bg-green-600 hover:bg-green-700 text-white px-6 py-3 rounded font-medium"
      >
        Generate This Week's Events
      </button>

      <button 
  onClick={cleanupDuplicates}
  className="bg-red-600 hover:bg-red-700 text-white px-6 py-3 rounded mb-6"
>
  Cleanup Duplicate Events
</button>

      {/* Add Rule Form */}
      <div className="bg-white p-6 rounded-xl shadow border">
        <h3 className="font-bold mb-4">Add New Rule</h3>

        <input className="w-full border p-3 rounded mb-3" placeholder="Title" value={title} onChange={e => setTitle(e.target.value)} />
        <textarea className="w-full border p-3 rounded mb-3" rows={3} placeholder="Description" value={description} onChange={e => setDescription(e.target.value)} />

        <select className="w-full border p-3 rounded mb-3" value={type} onChange={e => setType(e.target.value)}>
          <option value="weekly">Weekly</option>
          <option value="monthly">Monthly</option>
          <option value="fixed">Fixed Date</option>
        </select>

        {(type === "weekly" || type === "monthly") && (
          <select className="w-full border p-3 rounded mb-3" value={dayOfWeek} onChange={e => setDayOfWeek(e.target.value)}>
            <option value="sunday">Sunday</option>
            <option value="monday">Monday</option>
            <option value="tuesday">Tuesday</option>
            <option value="wednesday">Wednesday</option>
            <option value="thursday">Thursday</option>
            <option value="friday">Friday</option>
            <option value="saturday">Saturday</option>
          </select>
        )}

        {type === "monthly" && (
          <input className="w-full border p-3 rounded mb-3" type="number" min="1" max="5" value={weekOfMonth} onChange={e => setWeekOfMonth(Number(e.target.value))} />
        )}

        {type === "fixed" && (
          <input className="w-full border p-3 rounded mb-3" type="date" value={date} onChange={e => setDate(e.target.value)} />
        )}

        <input className="w-full border p-3 rounded mb-3" type="time" value={time} onChange={e => setTime(e.target.value)} />
        <input className="w-full border p-3 rounded mb-5" placeholder="Location" value={location} onChange={e => setLocation(e.target.value)} />

        <button onClick={addRule} disabled={uploading} className="w-full bg-blue-700 text-white py-3 rounded font-bold">
          {uploading ? "Saving..." : "Add Rule & Generate Event"}
        </button>
      </div>

      {/* Rules List */}
      <div>
        <h3 className="font-semibold mb-4">Existing Rules ({eventRules.length})</h3>

        {eventRules.map(rule => (
          <div key={rule.id} className="bg-white border rounded-xl shadow p-6 mb-4">
            {editingId === rule.id ? (
              <div>
                <input className="w-full border p-2 mb-3" value={editTitle} onChange={e => setEditTitle(e.target.value)} />
                <textarea className="w-full border p-2 mb-3" rows={3} value={editDescription} onChange={e => setEditDescription(e.target.value)} />
                <input className="w-full border p-2 mb-3" value={editLocation} onChange={e => setEditLocation(e.target.value)} />
                <input className="w-full border p-2 mb-3" type="time" value={editTime} onChange={e => setEditTime(e.target.value)} />
                <div className="flex gap-3">
                  <button onClick={() => saveRule(rule.id)} className="bg-green-700 text-white px-4 py-2 rounded">Save</button>
                  <button onClick={cancelEditing} className="bg-gray-600 text-white px-4 py-2 rounded">Cancel</button>
                </div>
              </div>
            ) : (
              <div>
                <h4 className="font-bold text-lg">{rule.title}</h4>
                <p className="text-gray-600">{rule.description}</p>
                <div className="text-sm text-gray-500 mt-2">
                  <p><strong>Type:</strong> {rule.type}</p>
                  <p><strong>Day:</strong> {rule.dayOfWeek}</p>
                  {rule.weekOfMonth && <p><strong>Week:</strong> {rule.weekOfMonth}</p>}
                  {rule.time && <p><strong>Time:</strong> {rule.time}</p>}
                  {rule.location && <p><strong>Location:</strong> {rule.location}</p>}
                </div>
                <div className="flex gap-3 mt-4">
                  <button onClick={() => startEditing(rule)} className="bg-blue-700 text-white px-4 py-2 rounded">Edit</button>
                  <button onClick={() => removeRule(rule.id)} className="bg-red-700 text-white px-4 py-2 rounded">Delete</button>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}